<?php

/*
 * This file is part of the Puli package.
 *
 * (c) Bernhard Schussek <bschussek@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Webmozart\Puli\Extension\Symfony\HttpKernel\CacheWarmer;

use Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerInterface;
use Twig_Environment;
use Webmozart\Puli\Locator\ResourceLocatorInterface;
use Webmozart\Puli\Resource\DirectoryResourceIterator;
use Webmozart\Puli\Resource\ResourceFilterIterator;

/**
 * Generates the Twig cache for all templates in the resource repository.
 *
 * This warmer must be registered after or instead of TemplateCacheCacheWarmer,
 * because it overrides some of the files generated by that cache warmer.
 *
 * @author Bernhard Schussek <bschussek@gmail.com>
 */
class TwigTemplateCacheWarmer implements CacheWarmerInterface
{
    /**
     * @var ResourceLocatorInterface
     */
    private $locator;

    /**
     * @var string
     */
    private $suffix;

    /**
     * @var Twig_Environment
     */
    private $twig;

    public function __construct(ResourceLocatorInterface $locator, $suffix = '.twig')
    {
        $this->locator = $locator;
        $this->suffix = $suffix;
    }

    /**
     * Sets the Twig environment used for loading the cache.
     *
     * @param Twig_Environment $twig
     */
    public function setEnvironment(Twig_Environment $twig)
    {
        $this->twig = $twig;
    }

    /**
     * Warms up the cache.
     *
     * @param string $cacheDir The cache directory
     *
     * @throws \RuntimeException If setEnvironment() wasn't called
     */
    public function warmUp($cacheDir)
    {
        if (null === $this->twig) {
            throw new \RuntimeException(
                'The Twig environment must be set using setEnvironment() '.
                'before warming up the cache.'
            );
        }

        $iterator = new ResourceFilterIterator(
            new \RecursiveIteratorIterator(
                new DirectoryResourceIterator($this->locator->get('/')),
                \RecursiveIteratorIterator::SELF_FIRST
            ),
            $this->suffix,
            ResourceFilterIterator::CURRENT_AS_PATH
                | ResourceFilterIterator::FILTER_BY_NAME
                | ResourceFilterIterator::MATCH_SUFFIX
        );

        foreach ($iterator as $path) {
            try {
                $this->twig->loadTemplate($path);
            } catch (\Twig_Error $e) {
                // Problem during compilation, stop
            }
        }
    }

    /**
     * Returns whether this warmer is optional or not.
     *
     * @return Boolean always true
     */
    public function isOptional()
    {
        return true;
    }
}
